package org.cs7is3.constants;

import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class Constants {
    public static final Map<String, String> REPLACEMENT_ENTITIES = Map.ofEntries(
            Map.entry("hyph", "-"),
            Map.entry("blank", " "),
            Map.entry("sect", "§"),
            Map.entry("para", "¶"),
            Map.entry("cir", "○"),
            Map.entry("rsquo", "’"),
            Map.entry("times", "x"),
            Map.entry("bull", "•"),
            Map.entry("ge", ">="),
            Map.entry("reg", "®"),
            Map.entry("cent", "¢"),
            Map.entry("amp", "&"),
            Map.entry("gt", ">"),
            Map.entry("lt", "<"),

            Map.entry("acirc", "â"),
            Map.entry("ncirc", "n̂"),
            Map.entry("atilde", "ã"),
            Map.entry("ntilde", "ñ"),
            Map.entry("otilde", "õ"),
            Map.entry("utilde", "ũ"),
            Map.entry("aacute", "á"),
            Map.entry("cacute", "ć"),
            Map.entry("eacute", "é"),
            Map.entry("Eacute", "É"),
            Map.entry("Gacute", "Ǵ"),
            Map.entry("iacute", "í"),
            Map.entry("lacute", "ĺ"),
            Map.entry("nacute", "ń"),
            Map.entry("oacute", "ó"),
            Map.entry("pacute", "ṕ"),
            Map.entry("racute", "ŕ"),
            Map.entry("sacute", "ś"),
            Map.entry("uacute", "ú"),
            Map.entry("ocirc", "ô"),
            Map.entry("auml", "ä"),
            Map.entry("euml", "ë"),
            Map.entry("Euml", "Ë"),
            Map.entry("iuml", "ï"),
            Map.entry("Iuml", "Ï"),
            Map.entry("Kuml", "K̈"),
            Map.entry("Ouml", "Ö"),
            Map.entry("ouml", "ö"),
            Map.entry("uuml", "ü"),
            Map.entry("Ccedil", "Ç"),
            Map.entry("ccedil", "ç"),
            Map.entry("agrave", "à"),
            Map.entry("Agrave", "À"),
            Map.entry("egrave", "è"),
            Map.entry("Egrave", "È"),
            Map.entry("igrave", "ì"),
            Map.entry("Ograve", "Ò"),
            Map.entry("ograve", "ò"),
            Map.entry("ugrave", "ù"),

            Map.entry("AElig", "Æ"),
            Map.entry("ap", "ª"),
            Map.entry("deg", "°"),
            Map.entry("ubreve", "ŭ"),
            Map.entry("Ubreve", "Ŭ"),
            Map.entry("egs", "ɛ"),
            Map.entry("els", "ɘ"),
            Map.entry("percnt", "%"),
            Map.entry("pound", "£"),
            Map.entry("yen", "¥"),
            Map.entry("agr", "α"),
            Map.entry("bgr", "β"),
            Map.entry("dgr", "δ"),
            Map.entry("egr", "ε"),
            Map.entry("ggr", "γ"),
            Map.entry("Ggr", "Γ"),
            Map.entry("kgr", "κ"),
            Map.entry("lgr", "λ"),
            Map.entry("mgr", "μ"),
            Map.entry("pgr", "π"),
            Map.entry("rgr", "ρ"),
            Map.entry("sgr", "σ"),
            Map.entry("tgr", "τ"),
            Map.entry("xgr", "ξ"),
            Map.entry("zgr", "ζ"),
            Map.entry("eegr", "η"),
            Map.entry("khgr", "χ"),
            Map.entry("phgr", "φ"),
            Map.entry("thgr", "θ"),
            Map.entry("ohm", "Ω"),
            Map.entry("Bgr", "Β"),
            Map.entry("Ngr", "Ν"),
            Map.entry("EEgr", "Η"),
            Map.entry("OHgr", "Ο"),
            Map.entry("PSgr", "Ψ"),
            Map.entry("Omacr", "Ō")
    );

    public static List<String> NEWS_STOP_WORDS = Arrays.asList(
            "a","an","and","are","as","at","be","but","by","for","if","in","into","is","it","no",
            "not","of","on","or","such","that","the","their","then","there","these","they","this",
            "to","was","will","with",
            "i","me","my","myself","we","our","ours","ourselves","you","your","yours","yourself",
            "yourselves","he","him","his","himself","she","her","hers","herself","its","itself",
            "them","their","theirs","themselves","what","which","who","whom","those","am","were",
            "been","being","have","has","had","having","do","does","did","doing","because","until",
            "while","with","about","against","between","through","during","before","after","above",
            "below","from","up","down","out","off","over","under","again","further","once","here",
            "where","why","how","all","any","both","each","few","more","most","other","some","no",
            "nor","only","own","same","so","than","too","very","s","t","can","just","don","should",
            "now", "mr", "mrs", "ms", "dr", "inc", "ltd", "corp", "co",
            "from", "said", "have", "ha", "he", "which", "it", "hi", "would","own",
            "r","be","those", "p","even","after","reported",
            "i", "we", "been", "were", "on", "who", "had", "more", "all", "other",
            "also", "up", "about", "than", "after", "some", "only", "over",
            "can", "you", "should", "so", "what", "because", "most", "our", "now",
            "through", "before", "for", "be", "she", "well", "must", "however",
            "against", "even", "while", "own", "where", "just", "each", "few",
            "both", "here", "how", "my", "your", "him", "its", "itself", "they",
            "their", "them", "then", "these", "this", "those", "too", "until", "very",
            "do", "did", "are", "am", "an", "and", "any", "as", "at", "by", "but",
            "down", "during", "further", "had", "has", "having", "if", "into",
            "no", "nor", "not", "off", "once", "or", "out", "over", "same", "so",
            "some", "such", "than", "the", "their", "them", "then", "there", "these",
            "they", "this", "those", "through", "to", "too", "under", "until", "up",
            "very", "was", "we", "were", "what", "when", "where", "which", "while",
            "who", "whom", "with", "you", "your", "yours", "yourself", "yourselves","d", "b","c", "i",
            "page", "text", "date", "sourc", "docno", "headlin", "part", "last",
            "state", "bylin", "includ", "compani", "column", "end", "per", "like",
            "issu", "follow", "profil", "pub", "section", "continu", "busi", "interest",
            "develop", "meet", "expect", "provid"
    );
}
